// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A class that exposes the [FirebaseOptions] for configuring Firebase
/// in your Flutter application based on the platform and environment.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace these credentials with your actual Firebase project credentials
    // You can get these from your Firebase Console
    
    return FirebaseOptions(
      apiKey: 'AIzaSyBtpTKlM02RgMVKDlTsDfzDUYdopO7gUks',
      appId: '1:535383184685:android:a568344348097ff762efa4',
      messagingSenderId: '535383184685',
      projectId: 'ecotrack-efd6e',
      authDomain: 'ecotrack-efd6e.firebaseapp.com',
      databaseURL: 'https://ecotrack-efd6e.firebaseio.com', // Firebase Realtime Database (optional)
      storageBucket: 'ecotrack-efd6e.appspot.com', // Firebase Cloud Storage (optional)
    );
  }
}
