/// Application configuration constants
/// 
/// For local development, update BACKEND_URL to your local backend
/// For production, update to your production backend URL
class AppConstants {
  // Backend API Configuration
  // Update this URL based on your environment:
  // - Local dev: http://localhost:8000
  // - Remote dev: https://your-devtunnel-url.uks1.devtunnels.ms
  // - Production: https://your-production-api.com
  static const String BACKEND_URL = 'https://zvhdw4k2-8000.uks1.devtunnels.ms';

  // Firebase Configuration
  // These are configured in firebase_options.dart
  // which is generated by FlutterFire CLI
  
  // API Endpoints
  static const String FIREBASE_REGISTER_ENDPOINT = '/api/v1/auth/firebase/register';
  static const String FIREBASE_VERIFY_ENDPOINT = '/api/v1/auth/firebase/verify';
  static const String PROFILE_ENDPOINT = '/api/v1/auth/profile';
  
  // WalletConnect — get free project ID from cloud.walletconnect.com
  static const String WALLETCONNECT_PROJECT_ID = 'fec5e6d06b78f02fa5ed0d0cd883b8e5';

  // App Configuration
  static const String APP_NAME = 'CoinTrack';
  static const String APP_VERSION = '1.0.0';
  
  // Timeouts (in seconds)
  static const int HTTP_TIMEOUT = 30;
  static const int AUTH_TOKEN_REFRESH_INTERVAL = 3300; // 55 minutes (tokens valid for 60)
}
