/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HashStoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getHashes"
      | "getStoredAt"
      | "hashExists"
      | "storeBatch"
      | "storeHash"
      | "storedAt"
      | "transactionHashes"
      | "verifyHash"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "HashStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "getHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStoredAt",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashExists",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeBatch",
    values: [BigNumberish, BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "storeHash",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storedAt",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transactionHashes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHash",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getHashes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStoredAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hashExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "storeBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "storeHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "storedAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactionHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
}

export namespace HashStoredEvent {
  export type InputTuple = [
    userId: BigNumberish,
    txId: BigNumberish,
    hash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    userId: bigint,
    txId: bigint,
    hash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    userId: bigint;
    txId: bigint;
    hash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HashStore extends BaseContract {
  connect(runner?: ContractRunner | null): HashStore;
  waitForDeployment(): Promise<this>;

  interface: HashStoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getHashes: TypedContractMethod<[userId: BigNumberish], [string[]], "view">;

  getStoredAt: TypedContractMethod<
    [txId: BigNumberish, hash: BytesLike],
    [bigint],
    "view"
  >;

  hashExists: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  storeBatch: TypedContractMethod<
    [userId: BigNumberish, txIds: BigNumberish[], hashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  storeHash: TypedContractMethod<
    [userId: BigNumberish, txId: BigNumberish, hash: BytesLike],
    [void],
    "nonpayable"
  >;

  storedAt: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [bigint],
    "view"
  >;

  transactionHashes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  verifyHash: TypedContractMethod<
    [txId: BigNumberish, hash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getHashes"
  ): TypedContractMethod<[userId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStoredAt"
  ): TypedContractMethod<
    [txId: BigNumberish, hash: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashExists"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "storeBatch"
  ): TypedContractMethod<
    [userId: BigNumberish, txIds: BigNumberish[], hashes: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeHash"
  ): TypedContractMethod<
    [userId: BigNumberish, txId: BigNumberish, hash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storedAt"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transactionHashes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [txId: BigNumberish, hash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "HashStored"
  ): TypedContractEvent<
    HashStoredEvent.InputTuple,
    HashStoredEvent.OutputTuple,
    HashStoredEvent.OutputObject
  >;

  filters: {
    "HashStored(uint256,uint256,bytes32,uint256)": TypedContractEvent<
      HashStoredEvent.InputTuple,
      HashStoredEvent.OutputTuple,
      HashStoredEvent.OutputObject
    >;
    HashStored: TypedContractEvent<
      HashStoredEvent.InputTuple,
      HashStoredEvent.OutputTuple,
      HashStoredEvent.OutputObject
    >;
  };
}
